website/auth.py
from flask import Blueprint, render_template, flash, redirect, url_for
from werkzeug.utils import redirect
from .models import User
from . import db, bcrypt, mail
from flask_login import login_user, login_required, logout_user, current_user
from .forms import RegistrationForm, LoginForm
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer
from flask import current_app
from datetime import datetime
from .emails import confirm_mail_text

auth = Blueprint('auth', __name__)


def generate_confirmation_token(email):
    s = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    return s.dumps(email, salt=current_app.config['SECURITY_PASSWORD_SALT'])


def confirm_token(token, expiration=3600):
    s = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    try:
        email = s.loads(
            token, salt=current_app.config['SECURITY_PASSWORD_SALT'], max_age=expiration)
    except:
        return False
    return email

# Get data via sing-up form for creating a new user


@auth.route('/sign_up', methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        new_user = User(name=form.name.data, email=form.email.data,
                        password=hashed_password, confirmed=False)
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember=True)
        send_confirmation_email(new_user.email)
        flash(
            f'Email confirmation link has been sent to {new_user.email}. Please check your email.', category='info')
        return redirect(url_for('views.home'))
    return render_template('sign_up.html', form=form)

# Email with a link for email confirmation


def send_confirmation_email(email):
    token = generate_confirmation_token(email)
    msg = Message('Email confirmation', recipients=[email])
    msg.html = confirm_mail_text(token)
    mail.send(msg)

# Url for email confirmation


@auth.route('/confirm/<token>')
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is expired. Try to sign up again',
              category='warning')
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
        return redirect(url_for('auth.login'))
    else:
        user.confirmed = True
        user.confirmed_on = datetime.utcnow()
        db.session.add(user)
        db.session.commit()
        flash(
            f'Account for {user.name} successfully confirmed!', category='success')
    return redirect(url_for('views.home'))


@auth.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect(url_for('views.home'))
    flash('Please confirm your account!', category='warning')
    return render_template('unconfirmed.html')


@auth.route('/resend')
@login_required
def resend_confirmation():
    send_confirmation_email(current_user.email)
    flash('A new confirmation email has been sent.', category='info')
    return redirect(url_for('auth.unconfirmed'))

# Implementation of login function


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            flash('You logged in successfully!', category='success')
            login_user(user, remember=form.remember.data)
            return redirect(url_for('views.home'))
        else:
            flash('Login unsuccessful. Please check email and password',
                  category='warning')
    return render_template('login.html', form=form, user=current_user)

# Logout user


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You logged out!', category='info')
    return redirect(url_for('views.welcome'))

website/views.py
from flask import Blueprint, render_template, flash, abort, url_for, request
from werkzeug.utils import redirect
from flask_login import login_required, current_user
from .models import User, Project, Entry
from . import db, mail, bcrypt
from .forms import AddProjectForm, EditProjectForm, EntryForm, ResetRequestForm, ResetPasswordForm
from .helper import adjust_data, check_confirmed
from sqlalchemy import extract, and_
from sqlalchemy.sql import func
from flask_mail import Message
import json
from datetime import datetime, timedelta
from .emails import reset_email_text

views = Blueprint('views', __name__)


@views.route('/')
def welcome():
    return render_template('welcome.html')


@views.route('/home', methods=['GET', 'POST'])
@login_required
@check_confirmed
def home():
    # Get data for pie-chart (for last 30 days projects)
    current_day = datetime.utcnow().date()
    a_day_30_days_ago = current_day - timedelta(days=30)
    recent_projects = (db.session.query(Project.project_name, db.func.sum(Entry.duration))
                       .join(Entry)
                       .filter(and_(Project.owner == current_user, Entry.date.between(a_day_30_days_ago, current_day)))
                       .group_by(Project.project_name)
                       .all()
                       )
    user_projects_l = []
    user_projects_d = []
    for project_name, minutes in recent_projects:
        user_projects_l.append(project_name)
        user_projects_d.append(round((minutes / 60), 1))
    no_entries_yet = True
    if user_projects_d:
        no_entries_yet = False
    user_projects_labels = json.dumps(user_projects_l)
    user_projects_data = json.dumps(user_projects_d)

    # Get data from "Add new project form", if the button pressed = POST request sent
    project_form = AddProjectForm()
    if project_form.validate_on_submit():
        user = Project.query.filter(
            Project.project_name == project_form.project_name.data, Project.user_id == current_user.id).first()
        if user:
            flash('Project already exists! Use another name', category='warning')
        else:
            new_project = Project(project_name=project_form.project_name.data,
                                  goal=project_form.goal.data, notes=project_form.notes.data, user_id=current_user.id)
            db.session.add(new_project)
            db.session.commit()
            flash('New project added!', category='success')

    return render_template("home.html",
                           user=current_user,
                           project_form=project_form,
                           user_projects_labels=user_projects_labels, user_projects_data=user_projects_data,
                           no_entries_yet=no_entries_yet,
                           )


# Individual page with a particular project data
@views.route('project/<int:project_id>', methods=['GET', 'POST'])
@login_required
@check_confirmed
def project(project_id):
    # Check page accessibility rights
    current_project = Project.query.filter(
        Project.id == project_id, Project.owner == current_user).first_or_404()
    if current_project.owner != current_user:
        abort(403)

    # Get last 5 queries made by the user to show in a table on the page
    last5 = Entry.query.join(Project).filter(and_(Entry.project_id == current_project.id,
                                                  Project.owner == current_user)
                                             ).order_by(Entry.timestamp.desc()).limit(5).all()
    current_day = datetime.now().date()

    # Get data for a "this week" chart
    last_monday = current_day - timedelta(days=current_day.weekday())
    current_week = last_monday.strftime(
        "%b %e") + ' - ' + (last_monday + timedelta(days=6)).strftime("%b %e")
    this_week_enries = (db.session.query(db.func.sum(Entry.duration), Entry.date)
                        .join(Project)
                        .filter(and_(Project.owner == current_user, Entry.project_id == project_id, Entry.date.between(last_monday, current_day)))
                        .group_by(Entry.date)
                        .order_by(Entry.date)
                        .all()
                        )
    this_week_d = []
    this_week_l = []
    for minute, date in this_week_enries:
        this_week_d.append(minute)
        this_week_l.append(date.strftime("%B %d"))
    thisweek_summ_hours = round((sum(this_week_d) / 60), 1)
    this_week_data = json.dumps(this_week_d)
    this_week_labels = json.dumps(this_week_l)

    # Get data for a "Last 30 days" chart
    a_day_30_days_ago = current_day - timedelta(days=30)
    this_month_enries = (db.session.query(db.func.sum(Entry.duration), Entry.date)
                         .join(Project)
                         .filter(and_(Project.owner == current_user, Entry.project_id == project_id, Entry.date.between(a_day_30_days_ago, current_day)))
                         .group_by(Entry.date)
                         .order_by(Entry.date)
                         .all()
                         )
    this_month_d = []
    this_month_l = []
    for minute, date in this_month_enries:
        this_month_d.append(round((minute / 60), 1))
        this_month_l.append(date.strftime("%b %e"))
    thismonth_summ_hours = round(sum(this_month_d), 1)
    this_month_data = json.dumps(this_month_d)
    this_month_labels = json.dumps(this_month_l)

    # Get data for a "Last 12 weeks" chart from database
    next_monday = current_day - \
        timedelta(days=current_day.weekday()) + timedelta(days=7)
    a_monday_84_days_ago = next_monday - timedelta(days=84)
    these_12weeks_entries = []
    these_12weeks_entries = (db.session.query(func.sum(Entry.duration), extract('week', Entry.date), extract('year', Entry.date))
                             .join(Project)
                             .filter(and_(Project.owner == current_user, Entry.project_id == project_id, Entry.date.between(a_monday_84_days_ago, next_monday)))
                             .group_by(extract('week', Entry.date))
                             .order_by(Entry.date)
                             .all()
                             )
    raw_these_12weeks_d = []
    these_12weeks_l = []
    raw_week_of_year_for_data = []
    add_to_adjacent = 0

    # If first few days of a year are recognized by database not as belonged to the first week of the year, but to a week 0,
    # in that case minutes worked on these days will be added to the last week of a previous year.
    # Or to the first week of a new year, if the last week is not present on the "Last 12 Weeks" chart.
    week_52 = False
    for minute, week, year in these_12weeks_entries:
        if week == 0:
            add_to_adjacent = round((minute / 60), 1)
        else:
            if week == 52:
                week_52 = True
            raw_these_12weeks_d.append(round((minute / 60), 1))
            raw_week_of_year_for_data.append([week, year])

    if not week_52:
        for i, week_and_year in enumerate(raw_week_of_year_for_data):
            if 1 in week_and_year:
                buff = raw_these_12weeks_d.pop(i)
                buff = buff + add_to_adjacent
                raw_these_12weeks_d.insert(i, buff)
    else:
        for i, week_and_year in enumerate(raw_week_of_year_for_data):
            if 52 in week_and_year:
                buff = raw_these_12weeks_d.pop(i)
                buff = buff + add_to_adjacent
                raw_these_12weeks_d.insert(i, buff)

    week_of_year_for_data = raw_week_of_year_for_data.copy()

    # Get 12 labels for "Last 12 weeks" chart, counting from current week Monday
    last_monday = current_day - timedelta(days=current_day.weekday())
    reversed_12weeks_l = [last_monday.strftime(
        "%b %e") + ' - ' + (last_monday + timedelta(days=6)).strftime("%b %e")]
    for week in range(1, 12):
        reversed_12weeks_l.append((last_monday - timedelta(days=7 * week)).strftime("%b %e") + ' - ' + (
            last_monday - timedelta(days=7 * week) + timedelta(days=6)).strftime("%b %e"))
    reversed_12weeks_l.reverse()
    these_12weeks_l = reversed_12weeks_l.copy()

    # Get numbers of weeks and years of those 12 labels got above
    week_of_year_for_labels = [
        [last_monday.isocalendar()[1], last_monday.isocalendar()[0]]]
    for week in range(1, len(these_12weeks_l)):
        week_of_year_for_labels.append([(last_monday - timedelta(days=7 * week)).isocalendar()[
                                       1], (last_monday - timedelta(days=7 * week)).isocalendar()[0]])
    week_of_year_for_labels.reverse()

    # Adjust data-set according to it's week labels by adding zeros to the skipped weeks without data:
    these_12weeks_d = adjust_data(
        week_of_year_for_data, raw_these_12weeks_d, week_of_year_for_labels)

    week_goal = 0
    # If hours per week Goal set(shows at "Last 12 Weeks" chart), additional data needed:
    # 1. Get the ideal expected progress line on the chart
    these_12weeks_d_goal = []
    # 2. Get the actual user progress line on the same chart
    these_12weeks_p = []
    if current_project.goal:
        goal = True
        week_goal = current_project.goal
        these_12weeks_d_goal = [week_goal]
        if these_12weeks_d:
            these_12weeks_p = [these_12weeks_d[0]]
        for week, _ in enumerate(these_12weeks_d):
            if week == 0:
                continue
            these_12weeks_p.append(
                these_12weeks_d[week] + these_12weeks_p[week - 1])
            these_12weeks_d_goal.append(week_goal*(week+1))
    else:
        goal = False

    # Pass all the data related to "Last 12 Weeks" chart to html
    these_12weeks_labels = json.dumps(these_12weeks_l)
    these_12weeks_data = json.dumps(these_12weeks_d)
    these12weeks_summ_hours = round(sum(these_12weeks_d), 1)
    these_12weeks_progress = json.dumps(these_12weeks_p)
    these_12weeks_data_goal = json.dumps(these_12weeks_d_goal)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" 
    crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootswatch@5.1.2/dist/flatly/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-primary py-2">
    <div class="container-xl">
      {% if user and user.is_authenticated %}
      <a class="navbar-brand" href="{{ url_for('views.home') }}">
      {% else %}
      <a class="navbar-brand" href="{{ url_for('views.welcome') }}">
      {% endif %}
        <img src="{{ url_for('static', filename='ypt_logo.svg') }}" class="img-fluid" alt="Your Project Tracker Logo" width="28" height="28" class="d-inline-block align-text-top">
        <span>Your Project Tracker</span>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end align-center" id="navbarColor01">
        <ul class="navbar-nav">
          {% if user and user.is_authenticated %}
            {% if project_id %}
              <li class="nav-item">
                <a class="nav-link fw-lighter" href="{{ url_for('views.add_time', project_id=project_id) }}">Add Time</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fw-lighter" href="{{ url_for('views.edit_project', project_id=project_id) }}">Edit Project</a>
              </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link fw-lighter" href="#addproject">Add New Project</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link fw-lighter" href="{{ url_for('views.home') }}">Home
                <span class="visually-hidden">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link fw-lighter" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissable text-center">
            {{ message }}
            <button type="button" class="btn-close mx-5" data-bs-dismiss="alert"></button>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

        {% block content %}{% endblock %}

  {% if footerfalse%}
  {% else %}
  <div class="container-fluid navbar fixed-bottom bg-primary text-white justify-content-center pt-2 pb-0">
    <h6 class="px-3">info@yourprojecttracker.com</h6>
    <p><a href="https://github.com/LiudmilaLV"><img class="img-fluid" src="{{ url_for('static', filename='GitHub.png') }}" alt="github logo" style="width:30px; height:30px;"></a></p>
  </div>
  {% endif %}     
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" 
    crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script>
    $(document).ready(function() {
      window.setTimeout(function() {
        $(".alert").fadeTo(500, 0).remove();
      }, 4000);
    });
  </script>
</body>
</html>

website/templates/change_password.html
{% extends "base.html" %}
{% block title %}Change Password{% endblock %}
{% block content %}
<div class="container my-3 col-md-4 center" >
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend>Change Password</legend>
            <div class="form-group">
                {{ form.password.label(class="form-label mt-4") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-label mt-4") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control") }}
                {% endif %}
            </div>
        </fieldset>
        <br>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<section class="container py-3 min-vh-100">        
    {% if not user.projects %}
    <!-- If User doesn't have any projects yet -->
    <div class="row d-flex flex-wrap justify-content-evenly">
        <div class="col-md-5 my-5">
            <h1 class="text-primary display-2">Hi, {{user.name}}!</h1>
        </div>
        <div class="col-md-6 my-5">
            <h3>Welcome to Your Project Tracker!</h3>
            <h6>A simple tool to measure time you spend on your projects and track your progress with infographics.</h6>
            <h5>No projects yet?</h5>
            <h5>Let's add one here below!</h5>
        </div>
    </div>
    {% else %} 
    <!-- If User has projects -->
    <div class="row d-flex flex-wrap justify-content-center">
        <div class="col-md-5">
            <div class="display-2 my-3 mt-5">Hi, {{user.name}}!</div>
            <h3 class="my-3">Your projects:</h3>
            <div class="d-flex flex-wrap justify-content-evenly align-content-evenly">
                {% for project in user.projects %}
                <a href="{{ url_for('views.project', project_id=project.id) }}">
                    <div class="btn btn-primary btn-lg my-2">
                    {{project.project_name}}
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-5">
            {% if no_entries_yet %}
                <h3 class="text-center mt-5">Here will be your progress data.</h3>
                <h5 class="text-center">Select a project and add some time to it!</h5>                
            {% else %}
            <h4 class="text-center">Last 30 Days Progress:</h4>
            <!-- Pie Chart -->
            <div class="chart my-3">
                <canvas id="projects_pie"></canvas>
            </div>
            {% endif %}
        </div>
    {% endif %}
    

    <div class="container my-5 py-5 col-md-6" id="addproject">
        <form method="POST" action="#">
            {{ project_form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                    {{ project_form.project_name.label(class="form-label mt-3") }}
                    {% if project_form.project_name.errors %}
                        {{ project_form.project_name(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in project_form.project_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ project_form.project_name(class="form-control") }}
                    {% endif %} 
                </div>
                <div class="form-group">
                    {{ project_form.goal.label(class="form-label mt-3") }}
                    {% if project_form.goal.errors %}
                        {{ project_form.goal(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in project_form.goal.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ project_form.goal(class="form-control") }}
                    {% endif %} 
                </div>
                <div class="form-group">
                    {{ project_form.notes.label(class="form-label mt-3") }}
                    {% if project_form.notes.errors %}
                        {{ project_form.notes(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in project_form.notes.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ project_form.notes(class="form-control") }}
                    {% endif %}
                </div>
            </fieldset>
            <br>
            <div class="form-group">
                {{ project_form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
</section>

{% block javascript %}
<script>
    let u_p_labels = JSON.parse({{ user_projects_labels | tojson }})
    let u_p_data = JSON.parse('{{ user_projects_data }}')

    const pie_data = {
    labels: u_p_labels,
    datasets: [{
    data: u_p_data,
    backgroundColor: [
        'rgb(24, 188, 156)',
        'rgb(243, 156, 18)',
        'rgb(231,76,60)',
        'rgb(37, 53, 68)',
        'rgb(52, 152, 219)',
        'rgb(75, 44, 133)'
    ],
    hoverOffset: 8
    }]
    };
    const pie_config = {
        type: 'pie',
        data: pie_data,
        options: {
        plugins: {
            subtitle: {
                display: true,
                text: 'Hours you spent working on'
            }
        }
    }
        };

    const projects_pie_chart = new Chart(document.getElementById('projects_pie'), pie_config);

</script>
{% endblock %}
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="container mt-3 col-md-4 center" >
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend>Login</legend>
            <div class="form-group">
                {{ form.email.label(class="form-label mt-2") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-label mt-2") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control") }}
                {% endif %}           
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <br>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
        <small class="text-muted ml-2">
            <a href="{{ url_for('views.reset_request') }}">Forgot password?</a>
        </small>
    </form>
    <br>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account? <a class="ml-2" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
        </small>
    </div>
</div>
{% endblock %}

website/templates/reset_request.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock %}
{% block content %}
<div class="container my-3 col-md-4 center" >
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend>Reset Password</legend>
            <div class="form-group">
                {{ form.email.label(class="form-label mt-4") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control") }}
                {% endif %}
            </div>
        </fieldset>
        <br>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
    <br>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account? <a class="ml-2" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
        </small>
    </div>
</div>
{% endblock %}

website/templates/unconfirmed.html
{% extends "base.html" %}
{% block title %}Unconfirmed email{% endblock %}
{% block content %}
    <div class="container my-5 col-md-8 text-center">
        <h4> You have not confirmed your account.</h4> 
        <h4>Please check your email (and your spam folder there) for a confirmation link.</h4>
        <br>
        <p>Did not get the email? <a href="{{url_for('auth.resend_confirmation')}}"> Send again</a>.</p>
    </div>
{% endblock%}

website/templates/welcome.html
{% extends "base.html" %}
{% block title %}Welcome to YPT{% endblock %}
{% block content %}
<div class="container min-vh-100">
    <div class="container col-md-10 my-5 mb-3 text-center">
        <h1>Welcome to Your Project Tracker! <img class="img-fluid" src="{{ url_for('static', filename='ypt_logo.svg') }}" alt="logo" width="90"></h1>
    </div>
    <div class="row d-flex flex-wrap justify-content-center">
        <div class="container col-md-6 my-3">
            <br>
            <h4>A minimalistic web-app to measure time you spend on your projects and track your progress with useful infographics.</h4>
        </div>
        <div class="container col-md-6 my-3">
            <ul>
                <li>Create an account</li>
                <li>Add projects to track</li>
                <li>Use a timer/stopwatch here online</li>
                <li>Or add minutes to a project manually</li>
                <li>Get "Last 30 Days Progress" pie chart with all your recent projects</li>
                <li>Watch your progress throughout a week, a month or a year</li>    
                <li>Set a weekly goal and get a scoreboard-like "Last 12 weeks" chart</li>    
            </ul>
        </div>
    </div>
    <div class="container col-md-8 my-5 pb-2 text-center">
            <h4>Please <a class="ml-2" href="{{ url_for('auth.sign_up') }}">Sign Up</a> to create an account or <a class="ml-2" href="{{ url_for('auth.login') }}">Login</a>, if you already have one.</h4>
    </div>
</div>
{% endblock%}